import {
  ConnectedCustomer,
  ConnectedSite,
  ConnectedAsset,
  ConnectedDevice,
  ConnectedDataSource,
  MachineDataParameter,
  TelemetryPoint,
  DataQualityRecord,
  ConnectedEvent,
  EventRule,
  ConnectedApiKey,
  ConnectedWebhook,
  AvailabilityReportRecord,
} from "@/types/connected-data";

export const MOCK_CONNECTED_CUSTOMERS: ConnectedCustomer[] = [
  {
    id: "cust-001",
    name: "ABC Mining Ltd",
    code: "CUST-ABC",
    industry: "Mining & Heavy Equipment",
    contact_person: "David Miller",
    email: "d.miller@abcmining.com",
    phone: "+1 (555) 234-5678",
    status: "ACTIVE",
    site_count: 2,
    asset_count: 54,
    device_count: 58,
    created_at: "2025-01-15T08:00:00Z",
  },
  {
    id: "cust-002",
    name: "Apex Energy Corp",
    code: "CUST-APEX",
    industry: "Power Generation & Utilities",
    contact_person: "Sarah Jenkins",
    email: "s.jenkins@apexenergy.io",
    phone: "+1 (555) 876-5432",
    status: "ACTIVE",
    site_count: 4,
    asset_count: 128,
    device_count: 142,
    created_at: "2025-03-22T10:30:00Z",
  },
  {
    id: "cust-003",
    name: "Global Logistics Hub",
    code: "CUST-GLH",
    industry: "Logistics & Fleet",
    contact_person: "Marcus Vance",
    email: "m.vance@globallogistics.com",
    phone: "+1 (555) 345-6789",
    status: "ACTIVE",
    site_count: 3,
    asset_count: 310,
    device_count: 310,
    created_at: "2025-06-10T14:15:00Z",
  },
  {
    id: "cust-004",
    name: "Titan Industrial Chemicals",
    code: "CUST-TIC",
    industry: "Chemical Processing",
    contact_person: "Elena Rostova",
    email: "elena.r@titanchem.de",
    phone: "+49 89 1234 5678",
    status: "ACTIVE",
    site_count: 1,
    asset_count: 42,
    device_count: 48,
    created_at: "2025-09-01T11:00:00Z",
  },
];

export const MOCK_CONNECTED_SITES: ConnectedSite[] = [
  {
    id: "site-001",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    name: "Mine Site A - Open Pit",
    code: "SITE-MSA",
    location: "Pilbara Region, WA",
    coordinates: "-22.3501, 118.4902",
    asset_count: 32,
    active_device_count: 34,
    status: "OPERATIONAL",
    created_at: "2025-01-16T09:00:00Z",
  },
  {
    id: "site-002",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    name: "Mine Site B - Underground",
    code: "SITE-MSB",
    location: "Kalgoorlie, WA",
    coordinates: "-30.7489, 121.4658",
    asset_count: 22,
    active_device_count: 24,
    status: "OPERATIONAL",
    created_at: "2025-02-01T11:20:00Z",
  },
  {
    id: "site-003",
    customer_id: "cust-002",
    customer_name: "Apex Energy Corp",
    name: "Substation 04 North",
    code: "SITE-SUB4",
    location: "Houston, TX",
    coordinates: "29.7604, -95.3698",
    asset_count: 48,
    active_device_count: 52,
    status: "OPERATIONAL",
    created_at: "2025-03-23T08:00:00Z",
  },
  {
    id: "site-004",
    customer_id: "cust-002",
    customer_name: "Apex Energy Corp",
    name: "Solar & Diesel Plant Delta",
    code: "SITE-SDPD",
    location: "Phoenix, AZ",
    coordinates: "33.4484, -112.0740",
    asset_count: 80,
    active_device_count: 90,
    status: "WARNING",
    created_at: "2025-04-10T12:00:00Z",
  },
  {
    id: "site-005",
    customer_id: "cust-003",
    customer_name: "Global Logistics Hub",
    name: "Central Logistics Terminal",
    code: "SITE-CLT",
    location: "Chicago, IL",
    coordinates: "41.8781, -87.6298",
    asset_count: 310,
    active_device_count: 310,
    status: "OPERATIONAL",
    created_at: "2025-06-11T10:00:00Z",
  },
];

export const MOCK_CONNECTED_ASSETS: ConnectedAsset[] = [
  {
    id: "asset-001",
    asset_code: "EXC-01",
    name: "CAT 6040 Excavator 01",
    type: "Heavy Hydraulic Excavator",
    manufacturer: "Caterpillar",
    model: "6040 FS",
    serial_number: "CAT6040-2024-9981",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    site_id: "site-001",
    site_name: "Mine Site A - Open Pit",
    installation_date: "2025-02-10",
    status: "CONNECTED",
    description: "Primary overburden excavator operating on shift 1 & 2",
    device_id: "dev-101",
    device_name: "Teltonika Heavy CAN Gateway",
    device_type: "CAN Gateway",
    connectivity_status: "ONLINE",
    last_communication: "5 seconds ago",
    protocol: "CAN",
    parameter_count: 18,
    data_frequency_sec: 1,
    data_quality_percent: 99.8,
    last_data_point: "2026-09-02T10:40:55Z",
  },
  {
    id: "asset-002",
    asset_code: "EXC-02",
    name: "Komatsu PC8000 Excavator 02",
    type: "Mining Excavator",
    manufacturer: "Komatsu",
    model: "PC8000-11",
    serial_number: "KM-PC8K-8812",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    site_id: "site-001",
    site_name: "Mine Site A - Open Pit",
    installation_date: "2025-03-01",
    status: "CONNECTED",
    device_id: "dev-102",
    device_name: "Advantech Industrial Edge Gateway",
    device_type: "Industrial Gateway",
    connectivity_status: "ONLINE",
    last_communication: "3 seconds ago",
    protocol: "J1939",
    description: "High-capacity loading shovel",
    parameter_count: 22,
    data_frequency_sec: 1,
    data_quality_percent: 99.5,
    last_data_point: "2026-09-02T10:40:57Z",
  },
  {
    id: "asset-003",
    asset_code: "GEN-01",
    name: "Cummins QSK60 Generator 01",
    type: "Diesel Power Generator",
    manufacturer: "Cummins",
    model: "QSK60-G23",
    serial_number: "CUM-QSK60-4410",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    site_id: "site-001",
    site_name: "Mine Site A - Open Pit",
    installation_date: "2025-01-20",
    status: "CONNECTED",
    description: "Backup power generation unit for pit dewatering pumps",
    device_id: "dev-103",
    device_name: "Moxa Modbus TCP Gateway",
    device_type: "Modbus Bridge",
    connectivity_status: "ONLINE",
    last_communication: "8 seconds ago",
    protocol: "Modbus",
    parameter_count: 14,
    data_frequency_sec: 5,
    data_quality_percent: 98.9,
    last_data_point: "2026-09-02T10:40:50Z",
  },
  {
    id: "asset-004",
    asset_code: "GEN-02",
    name: "Perkins 2000 kVA Generator 02",
    type: "Standby Genset",
    manufacturer: "Perkins",
    model: "4016-61TRG",
    serial_number: "PER-4016-1102",
    customer_id: "cust-002",
    customer_name: "Apex Energy Corp",
    site_id: "site-004",
    site_name: "Solar & Diesel Plant Delta",
    installation_date: "2025-04-15",
    status: "DEGRADED",
    description: "Peaker plant genset unit 2",
    device_id: "dev-104",
    device_name: "HMS Anybus OPC-UA Gateway",
    device_type: "PLC Gateway",
    connectivity_status: "WARNING",
    last_communication: "45 seconds ago",
    protocol: "OPC-UA",
    parameter_count: 16,
    data_frequency_sec: 10,
    data_quality_percent: 91.2,
    last_data_point: "2026-09-02T10:40:10Z",
  },
  {
    id: "asset-005",
    asset_code: "COMP-01",
    name: "Atlas Copco GA160 Air Compressor",
    type: "Rotary Screw Air Compressor",
    manufacturer: "Atlas Copco",
    model: "GA160 VSD+",
    serial_number: "AC-GA160-5590",
    customer_id: "cust-004",
    customer_name: "Titan Industrial Chemicals",
    site_id: "site-004",
    site_name: "Solar & Diesel Plant Delta",
    installation_date: "2025-09-05",
    status: "OFFLINE",
    description: "Instrument air supply compressor",
    device_id: "dev-105",
    device_name: "Siemens IoT2050 Gateway",
    device_type: "Edge Controller",
    connectivity_status: "OFFLINE",
    last_communication: "24 minutes ago",
    protocol: "MQTT",
    parameter_count: 12,
    data_frequency_sec: 2,
    data_quality_percent: 74.0,
    last_data_point: "2026-09-02T10:16:00Z",
  },
];

export const MOCK_CONNECTED_DEVICES: ConnectedDevice[] = [
  {
    id: "dev-101",
    device_id: "DEV-TEL-9001",
    name: "Teltonika Heavy CAN Gateway",
    imei: "867492048192019",
    serial_number: "FMB640-001928",
    manufacturer: "Teltonika Telematics",
    model: "FMB640",
    firmware_version: "v03.28.12.RevB",
    device_type: "CAN Gateway",
    protocol: "CAN",
    assigned_asset_id: "asset-001",
    assigned_asset_name: "CAT 6040 Excavator 01",
    assigned_site_id: "site-001",
    assigned_site_name: "Mine Site A - Open Pit",
    installation_date: "2025-02-10",
    last_seen: "2026-09-02T10:41:00Z",
    connection_status: "ONLINE",
    signal_strength_dbm: -68,
    battery_percent: 98,
    ip_address: "192.168.10.45",
    configuration_json: JSON.stringify(
      {
        can_baudrate: 250000,
        j1939_enabled: true,
        polling_rate_hz: 1,
        mqtt_topic: "telemetry/abcmining/exc01",
      },
      null,
      2,
    ),
  },
  {
    id: "dev-102",
    device_id: "DEV-ADV-4402",
    name: "Advantech Industrial Edge Gateway",
    imei: "863019284756302",
    serial_number: "UNO-2271G-0021",
    manufacturer: "Advantech",
    model: "UNO-2271G",
    firmware_version: "v2.1.0-Ubuntu-IoT",
    device_type: "Industrial Gateway",
    protocol: "J1939",
    assigned_asset_id: "asset-002",
    assigned_asset_name: "Komatsu PC8000 Excavator 02",
    assigned_site_id: "site-001",
    assigned_site_name: "Mine Site A - Open Pit",
    installation_date: "2025-03-01",
    last_seen: "2026-09-02T10:41:02Z",
    connection_status: "ONLINE",
    signal_strength_dbm: -72,
    battery_percent: 100,
    ip_address: "10.0.4.12",
    configuration_json: JSON.stringify(
      {
        edge_processing: true,
        buffer_size_mb: 512,
        sync_interval_ms: 1000,
      },
      null,
      2,
    ),
  },
  {
    id: "dev-103",
    device_id: "DEV-MOX-1109",
    name: "Moxa Modbus TCP Gateway",
    imei: "N/A - Ethernet",
    serial_number: "MGate-5105-8812",
    manufacturer: "Moxa Inc.",
    model: "MGate 5105-MB-EIP",
    firmware_version: "v3.4.1 Build 2209",
    device_type: "Modbus Bridge",
    protocol: "Modbus",
    assigned_asset_id: "asset-003",
    assigned_asset_name: "Cummins QSK60 Generator 01",
    assigned_site_id: "site-001",
    assigned_site_name: "Mine Site A - Open Pit",
    installation_date: "2025-01-20",
    last_seen: "2026-09-02T10:40:52Z",
    connection_status: "ONLINE",
    signal_strength_dbm: -55,
    battery_percent: null,
    ip_address: "192.168.20.104",
    configuration_json: JSON.stringify(
      {
        modbus_mode: "RTU_TO_TCP",
        slave_id: 1,
        baud_rate: 9600,
      },
      null,
      2,
    ),
  },
  {
    id: "dev-104",
    device_id: "DEV-HMS-8820",
    name: "HMS Anybus OPC-UA Gateway",
    imei: "N/A - Ethernet",
    serial_number: "AB-6002-C",
    manufacturer: "HMS Networks",
    model: "Anybus Communicator",
    firmware_version: "v4.0.2",
    device_type: "PLC Gateway",
    protocol: "OPC-UA",
    assigned_asset_id: "asset-004",
    assigned_asset_name: "Perkins 2000 kVA Generator 02",
    assigned_site_id: "site-004",
    assigned_site_name: "Solar & Diesel Plant Delta",
    installation_date: "2025-04-15",
    last_seen: "2026-09-02T10:40:15Z",
    connection_status: "WARNING",
    signal_strength_dbm: -88,
    battery_percent: null,
    ip_address: "10.10.8.22",
    configuration_json: JSON.stringify(
      {
        opc_endpoint: "opc.tcp://10.10.8.22:4840",
        security_policy: "Basic256Sha256",
      },
      null,
      2,
    ),
  },
  {
    id: "dev-105",
    device_id: "DEV-SIE-9901",
    name: "Siemens IoT2050 Gateway",
    imei: "869201938475620",
    serial_number: "SIM-IOT2050-771",
    manufacturer: "Siemens AG",
    model: "SIMATIC IOT2050",
    firmware_version: "v1.2.2-Industrial-OS",
    device_type: "Edge Controller",
    protocol: "MQTT",
    assigned_asset_id: "asset-005",
    assigned_asset_name: "Atlas Copco GA160 Air Compressor",
    assigned_site_id: "site-004",
    assigned_site_name: "Solar & Diesel Plant Delta",
    installation_date: "2025-09-05",
    last_seen: "2026-09-02T10:16:00Z",
    connection_status: "OFFLINE",
    signal_strength_dbm: -105,
    battery_percent: 12,
    ip_address: "10.10.9.15",
    configuration_json: JSON.stringify(
      {
        broker: "mqtt.machinecare.io:8883",
        keep_alive: 60,
      },
      null,
      2,
    ),
  },
];

export const MOCK_DATA_SOURCES: ConnectedDataSource[] = [
  {
    id: "ds-001",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    source_name: "CAN Bus J1939 Engine Line",
    protocol: "CAN",
    status: "ACTIVE",
    parameters_count: 12,
    polling_interval_sec: 1,
    last_sync: "2 seconds ago",
    endpoint_or_channel: "can0 / Baud 250k",
  },
  {
    id: "ds-002",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    source_name: "Hydraulic Pressure Transducer Array",
    protocol: "Analog Input",
    status: "ACTIVE",
    parameters_count: 4,
    polling_interval_sec: 1,
    last_sync: "2 seconds ago",
    endpoint_or_channel: "ADC Ch 1-4 / 4-20mA",
  },
  {
    id: "ds-003",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    source_name: "High Precision GPS Tracker",
    protocol: "GPS",
    status: "ACTIVE",
    parameters_count: 2,
    polling_interval_sec: 5,
    last_sync: "5 seconds ago",
    endpoint_or_channel: "GNSS NMEA-0183",
  },
  {
    id: "ds-004",
    asset_id: "asset-003",
    asset_name: "Cummins QSK60 Generator 01",
    source_name: "DeepSea Generator Controller 8610",
    protocol: "Modbus",
    status: "ACTIVE",
    parameters_count: 14,
    polling_interval_sec: 5,
    last_sync: "8 seconds ago",
    endpoint_or_channel: "Modbus RTU RS485 / Slave 1",
  },
  {
    id: "ds-005",
    asset_id: "asset-005",
    asset_name: "Atlas Copco GA160 Air Compressor",
    source_name: "Elektronikon MK5 Telemetry",
    protocol: "MQTT",
    status: "ERROR",
    parameters_count: 12,
    polling_interval_sec: 2,
    last_sync: "24 minutes ago",
    endpoint_or_channel: "mqtts://broker.ac.com/ga160",
  },
];

export const MOCK_MACHINE_DICTIONARY: MachineDataParameter[] = [
  {
    id: "param-101",
    standard_key: "engine_coolant_temperature",
    parameter_name: "Engine Coolant Temperature",
    display_name: "Engine Temperature",
    unit: "°C",
    data_type: "numeric",
    category: "Engine",
    min_value: -20,
    max_value: 120,
    expected_frequency_sec: 1,
    description: "Internal engine cooling system liquid temperature",
    raw_mapping_keys: ["engine_temp", "coolant_temp", "ECT", "eng_temp_c", "SPN_110"],
    quality_rules: "Range [-20 to 120 °C]; Rate Limit max delta 5 °C/sec",
  },
  {
    id: "param-102",
    standard_key: "engine_speed_rpm",
    parameter_name: "Engine Speed (RPM)",
    display_name: "Engine RPM",
    unit: "RPM",
    data_type: "numeric",
    category: "Engine",
    min_value: 0,
    max_value: 3500,
    expected_frequency_sec: 1,
    description: "Crankshaft rotational speed in revolutions per minute",
    raw_mapping_keys: ["engine_rpm", "RPM", "eng_speed", "SPN_190", "crank_speed"],
    quality_rules: "Range [0 to 3500 RPM]",
  },
  {
    id: "param-103",
    standard_key: "fuel_tank_level_percent",
    parameter_name: "Fuel Tank Level Percentage",
    display_name: "Fuel Level",
    unit: "%",
    data_type: "numeric",
    category: "Fluid",
    min_value: 0,
    max_value: 100,
    expected_frequency_sec: 5,
    description: "Remaining fuel percentage in primary reservoir",
    raw_mapping_keys: ["fuel_level", "fuel_pct", "FL_PCT", "SPN_96"],
    quality_rules: "Range [0 to 100 %]; Monotonic decrease during engine operation",
  },
  {
    id: "param-104",
    standard_key: "battery_terminal_voltage",
    parameter_name: "Battery Terminal Voltage",
    display_name: "Battery Voltage",
    unit: "V",
    data_type: "numeric",
    category: "Electrical",
    min_value: 0,
    max_value: 36,
    expected_frequency_sec: 5,
    description: "Direct current voltage across alternator/battery system",
    raw_mapping_keys: ["battery_voltage", "batt_volt", "v_batt", "SPN_168"],
    quality_rules: "Range [10 to 32 V]",
  },
  {
    id: "param-105",
    standard_key: "engine_operating_hours",
    parameter_name: "Total Engine Operating Hours",
    display_name: "Engine Hours",
    unit: "h",
    data_type: "numeric",
    category: "Operational",
    min_value: 0,
    max_value: 100000,
    expected_frequency_sec: 60,
    description: "Cumulative engine runtime counter",
    raw_mapping_keys: ["engine_hours", "total_hours", "hr_meter", "SPN_247"],
    quality_rules: "Strict non-decreasing accumulation",
  },
  {
    id: "param-106",
    standard_key: "generator_active_load_percent",
    parameter_name: "Generator Active Load Percentage",
    display_name: "Active Load",
    unit: "%",
    data_type: "numeric",
    category: "Electrical",
    min_value: 0,
    max_value: 150,
    expected_frequency_sec: 2,
    description: "Power electrical output relative to rated generator power",
    raw_mapping_keys: ["generator_load", "load_pct", "active_load", "pwr_pct"],
    quality_rules: "Range [0 to 125 %]",
  },
  {
    id: "param-107",
    standard_key: "ac_output_frequency_hz",
    parameter_name: "AC Output Frequency",
    display_name: "Frequency",
    unit: "Hz",
    data_type: "numeric",
    category: "Electrical",
    min_value: 40,
    max_value: 70,
    expected_frequency_sec: 2,
    description: "Generated AC grid frequency",
    raw_mapping_keys: ["frequency_hz", "ac_freq", "grid_freq", "hz_output"],
    quality_rules: "Range [45 to 65 Hz]",
  },
  {
    id: "param-108",
    standard_key: "hydraulic_oil_temperature",
    parameter_name: "Hydraulic Oil Temperature",
    display_name: "Hydraulic Temp",
    unit: "°C",
    data_type: "numeric",
    category: "Fluid",
    min_value: -10,
    max_value: 110,
    expected_frequency_sec: 2,
    description: "Hydraulic fluid reservoir temperature",
    raw_mapping_keys: ["hydr_temp", "hydraulic_oil_temp", "hyd_c"],
    quality_rules: "Range [0 to 100 °C]",
  },
];

export const MOCK_TELEMETRY_POINTS: Record<string, TelemetryPoint[]> = {
  "asset-001": [
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "engine_coolant_temperature",
      display_name: "Engine Temperature",
      value: 87.4,
      unit: "°C",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "engine_speed_rpm",
      display_name: "Engine RPM",
      value: 1502,
      unit: "RPM",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "fuel_tank_level_percent",
      display_name: "Fuel Level",
      value: 68.5,
      unit: "%",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "battery_terminal_voltage",
      display_name: "Battery Voltage",
      value: 24.7,
      unit: "V",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "engine_operating_hours",
      display_name: "Engine Hours",
      value: 4281,
      unit: "h",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "generator_active_load_percent",
      display_name: "Active Load",
      value: 74.2,
      unit: "%",
      quality_state: "GOOD",
    },
    {
      timestamp: "2026-09-02T10:41:00Z",
      asset_id: "asset-001",
      asset_name: "CAT 6040 Excavator 01",
      parameter_key: "hydraulic_oil_temperature",
      display_name: "Hydraulic Temp",
      value: 64.1,
      unit: "°C",
      quality_state: "GOOD",
    },
  ],
};

export const MOCK_DATA_QUALITY_RECORDS: DataQualityRecord[] = [
  {
    id: "dq-001",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    parameter_key: "engine_coolant_temperature",
    parameter_name: "Engine Coolant Temperature",
    quality_state: "GOOD",
    missing_count_24h: 2,
    delayed_count_24h: 12,
    invalid_count_24h: 0,
    stale_seconds: 1,
    quality_score_percent: 99.8,
    last_checked: "2026-09-02T10:40:00Z",
  },
  {
    id: "dq-002",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    parameter_key: "fuel_tank_level_percent",
    parameter_name: "Fuel Tank Level Percentage",
    quality_state: "WARNING",
    missing_count_24h: 18,
    delayed_count_24h: 44,
    invalid_count_24h: 1,
    stale_seconds: 5,
    quality_score_percent: 92.4,
    last_checked: "2026-09-02T10:40:00Z",
  },
  {
    id: "dq-003",
    asset_id: "asset-003",
    asset_name: "Cummins QSK60 Generator 01",
    parameter_key: "oil_pressure_bar",
    parameter_name: "Engine Oil Pressure",
    quality_state: "MISSING",
    missing_count_24h: 1420,
    delayed_count_24h: 88,
    invalid_count_24h: 0,
    stale_seconds: 1800,
    quality_score_percent: 64.2,
    last_checked: "2026-09-02T10:40:00Z",
  },
  {
    id: "dq-004",
    asset_id: "asset-004",
    asset_name: "Perkins 2000 kVA Generator 02",
    parameter_key: "ac_output_frequency_hz",
    parameter_name: "AC Output Frequency",
    quality_state: "DELAYED",
    missing_count_24h: 84,
    delayed_count_24h: 310,
    invalid_count_24h: 4,
    stale_seconds: 45,
    quality_score_percent: 88.5,
    last_checked: "2026-09-02T10:40:00Z",
  },
  {
    id: "dq-005",
    asset_id: "asset-005",
    asset_name: "Atlas Copco GA160 Air Compressor",
    parameter_key: "discharge_air_pressure",
    parameter_name: "Discharge Air Pressure",
    quality_state: "INVALID",
    missing_count_24h: 4200,
    delayed_count_24h: 800,
    invalid_count_24h: 140,
    stale_seconds: 1440,
    quality_score_percent: 41.0,
    last_checked: "2026-09-02T10:40:00Z",
  },
];

export const MOCK_CONNECTED_EVENTS: ConnectedEvent[] = [
  {
    id: "evt-001",
    event_code: "EVT-TEMP-091",
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    customer_name: "ABC Mining Ltd",
    site_name: "Mine Site A - Open Pit",
    parameter_key: "engine_coolant_temperature",
    parameter_name: "Engine Coolant Temperature",
    triggered_value: "98.4 °C",
    threshold: "> 95.0 °C for 5 min",
    timestamp: "2026-09-02T10:14:22Z",
    severity: "CRITICAL",
    status: "ACTIVE",
    description: "HIGH TEMPERATURE EVENT: Coolant temperature exceeded safety limit during heavy incline excavation.",
    source_rule_name: "Overheat Protection Alert Rule",
  },
  {
    id: "evt-002",
    event_code: "EVT-FUEL-088",
    asset_id: "asset-003",
    asset_name: "Cummins QSK60 Generator 01",
    customer_name: "ABC Mining Ltd",
    site_name: "Mine Site A - Open Pit",
    parameter_key: "fuel_tank_level_percent",
    parameter_name: "Fuel Tank Level Percentage",
    triggered_value: "14.2 %",
    threshold: "< 15.0 %",
    timestamp: "2026-09-02T09:45:00Z",
    severity: "WARNING",
    status: "ACTIVE",
    description: "LOW FUEL ALERT: Backup generator fuel reserve below 15% operational threshold.",
    source_rule_name: "Generator Fuel Warning",
  },
  {
    id: "evt-003",
    event_code: "EVT-OFFLINE-044",
    asset_id: "asset-005",
    asset_name: "Atlas Copco GA160 Air Compressor",
    customer_name: "Titan Industrial Chemicals",
    site_name: "Solar & Diesel Plant Delta",
    parameter_key: "device_heartbeat",
    parameter_name: "Device Connection",
    triggered_value: "Offline",
    threshold: "No ping > 10 min",
    timestamp: "2026-09-02T10:16:00Z",
    severity: "WARNING",
    status: "ACTIVE",
    description: "DEVICE OFFLINE EVENT: Siemens IoT2050 Gateway lost network connection.",
    source_rule_name: "Gateway Liveness Monitor",
  },
  {
    id: "evt-004",
    event_code: "EVT-VOLT-012",
    asset_id: "asset-004",
    asset_name: "Perkins 2000 kVA Generator 02",
    customer_name: "Apex Energy Corp",
    site_name: "Solar & Diesel Plant Delta",
    parameter_key: "battery_terminal_voltage",
    parameter_name: "Battery Terminal Voltage",
    triggered_value: "21.2 V",
    threshold: "< 22.0 V",
    timestamp: "2026-09-02T08:30:10Z",
    severity: "INFO",
    status: "RESOLVED",
    description: "LOW BATTERY VOLTAGE: Starter battery charging line drop detected.",
    source_rule_name: "Battery Health Check",
  },
];

export const MOCK_EVENT_RULES: EventRule[] = [
  {
    id: "rule-001",
    name: "Overheat Protection Alert Rule",
    asset_id: "ALL",
    asset_name: "All Assets",
    parameter_key: "engine_coolant_temperature",
    operator: ">",
    threshold: 95.0,
    unit: "°C",
    duration_minutes: 5,
    actions: {
      create_event: true,
      send_email: true,
      send_notification: true,
      trigger_webhook: true,
      create_work_order: false,
    },
    active: true,
    created_at: "2025-02-01T00:00:00Z",
  },
  {
    id: "rule-002",
    name: "Generator Fuel Warning",
    asset_id: "ALL",
    asset_name: "All Generators",
    parameter_key: "fuel_tank_level_percent",
    operator: "<",
    threshold: 15.0,
    unit: "%",
    duration_minutes: 1,
    actions: {
      create_event: true,
      send_email: true,
      send_notification: true,
      trigger_webhook: false,
      create_work_order: false,
    },
    active: true,
    created_at: "2025-02-15T00:00:00Z",
  },
  {
    id: "rule-003",
    name: "Gateway Liveness Monitor",
    asset_id: "ALL",
    asset_name: "All Gateways",
    parameter_key: "device_offline",
    operator: "device_offline",
    threshold: 10,
    unit: "min",
    duration_minutes: 10,
    actions: {
      create_event: true,
      send_email: false,
      send_notification: true,
      trigger_webhook: true,
      create_work_order: false,
    },
    active: true,
    created_at: "2025-03-01T00:00:00Z",
  },
];

export const MOCK_API_KEYS: ConnectedApiKey[] = [
  {
    id: "key-001",
    name: "Apex Analytics Platform Integration",
    key_prefix: "mc_live_8f3a...",
    full_key: "mc_live_8f3a9921b40294e10294857102938475",
    customer_id: "cust-002",
    customer_name: "Apex Energy Corp",
    scopes: ["assets:read", "telemetry:read", "events:read", "alerts:read", "sites:read"],
    created_at: "2025-04-01T10:00:00Z",
    expires_at: "2027-04-01T10:00:00Z",
    last_used_at: "2 minutes ago",
    status: "ACTIVE",
  },
  {
    id: "key-002",
    name: "ABC Mining Data Science API Key",
    key_prefix: "mc_live_1c9b...",
    full_key: "mc_live_1c9b0019284756201928374650192837",
    customer_id: "cust-001",
    customer_name: "ABC Mining Ltd",
    scopes: ["telemetry:read", "assets:read"],
    created_at: "2025-05-12T14:30:00Z",
    expires_at: "2026-12-31T23:59:59Z",
    last_used_at: "1 hour ago",
    status: "ACTIVE",
  },
];

export const MOCK_WEBHOOKS: ConnectedWebhook[] = [
  {
    id: "wh-001",
    name: "Datadog Telemetry Alert Stream",
    target_url: "https://api.datadoghq.com/api/v1/input/mc_hook_881",
    events_subscribed: ["high_temperature", "device_offline", "low_fuel"],
    secret: "whsec_99182746501928374650192",
    status: "ACTIVE",
    total_deliveries: 14820,
    failed_deliveries: 3,
    last_delivery_at: "14 seconds ago",
  },
  {
    id: "wh-002",
    name: "AWS Lambda Anomaly Pipeline",
    target_url: "https://hooks.us-east-1.amazonaws.com/telemetry/ingest",
    events_subscribed: ["data_quality_degraded", "high_vibration"],
    secret: "whsec_11029384756102938475",
    status: "ACTIVE",
    total_deliveries: 4210,
    failed_deliveries: 0,
    last_delivery_at: "5 minutes ago",
  },
];

export const MOCK_AVAILABILITY_REPORTS: AvailabilityReportRecord[] = [
  {
    asset_id: "asset-001",
    asset_name: "CAT 6040 Excavator 01",
    customer_name: "ABC Mining Ltd",
    site_name: "Mine Site A - Open Pit",
    expected_datapoints_24h: 86400,
    received_datapoints_24h: 86220,
    availability_percent: 99.79,
    uptime_hours: 23.95,
    offline_hours: 0.05,
    network_quality_score: 99.8,
  },
  {
    asset_id: "asset-002",
    asset_name: "Komatsu PC8000 Excavator 02",
    customer_name: "ABC Mining Ltd",
    site_name: "Mine Site A - Open Pit",
    expected_datapoints_24h: 86400,
    received_datapoints_24h: 85930,
    availability_percent: 99.45,
    uptime_hours: 23.87,
    offline_hours: 0.13,
    network_quality_score: 99.2,
  },
  {
    asset_id: "asset-003",
    asset_name: "Cummins QSK60 Generator 01",
    customer_name: "ABC Mining Ltd",
    site_name: "Mine Site A - Open Pit",
    expected_datapoints_24h: 17280,
    received_datapoints_24h: 17090,
    availability_percent: 98.90,
    uptime_hours: 23.74,
    offline_hours: 0.26,
    network_quality_score: 98.0,
  },
  {
    asset_id: "asset-004",
    asset_name: "Perkins 2000 kVA Generator 02",
    customer_name: "Apex Energy Corp",
    site_name: "Solar & Diesel Plant Delta",
    expected_datapoints_24h: 8640,
    received_datapoints_24h: 7880,
    availability_percent: 91.20,
    uptime_hours: 21.88,
    offline_hours: 2.12,
    network_quality_score: 89.5,
  },
  {
    asset_id: "asset-005",
    asset_name: "Atlas Copco GA160 Air Compressor",
    customer_name: "Titan Industrial Chemicals",
    site_name: "Solar & Diesel Plant Delta",
    expected_datapoints_24h: 43200,
    received_datapoints_24h: 31968,
    availability_percent: 74.00,
    uptime_hours: 17.76,
    offline_hours: 6.24,
    network_quality_score: 72.1,
  },
];

export function generateHistoricalTimeSeries(
  assetId: string,
  paramKey: string,
  timeframe: "1h" | "24h" | "7d" | "30d",
) {
  const pointsCount = timeframe === "1h" ? 30 : timeframe === "24h" ? 48 : timeframe === "7d" ? 56 : 60;
  const now = new Date();
  const stepMs =
    timeframe === "1h"
      ? 2 * 60 * 1000
      : timeframe === "24h"
      ? 30 * 60 * 1000
      : timeframe === "7d"
      ? 3 * 3600 * 1000
      : 12 * 3600 * 1000;

  const data = [];
  let baseVal = 80;
  if (paramKey === "engine_speed_rpm") baseVal = 1450;
  if (paramKey === "fuel_tank_level_percent") baseVal = 75;
  if (paramKey === "battery_terminal_voltage") baseVal = 24.8;
  if (paramKey === "generator_active_load_percent") baseVal = 70;
  if (paramKey === "ac_output_frequency_hz") baseVal = 50.0;

  for (let i = pointsCount - 1; i >= 0; i--) {
    const time = new Date(now.getTime() - i * stepMs);
    const noise = (Math.random() - 0.48) * (baseVal > 100 ? 50 : 3);
    let val = Math.max(0, parseFloat((baseVal + noise).toFixed(2)));
    if (paramKey === "fuel_tank_level_percent") {
      val = Math.max(10, parseFloat((baseVal - (pointsCount - i) * 0.4).toFixed(1)));
    }
    data.push({
      timestamp: time.toISOString(),
      formattedTime:
        timeframe === "1h" || timeframe === "24h"
          ? time.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
          : time.toLocaleDateString([], { month: "short", day: "numeric" }),
      value: val,
      secondaryValue: parseFloat((val * 0.85 + Math.random() * 2).toFixed(1)),
      tertiaryValue: parseFloat((val * 1.1 + Math.random() * 5).toFixed(1)),
    });
  }
  return data;
}
